print('¿Qué sale de la cruza entre un mono y un pato?')
input()
print('¡ Un monopatín!')
print()
print('¿Por qué vuelan los pájaros pa\'l sur?')
input()
print('¡Porque caminando tardarían muchísimo!')
print()
print('¿En qué parecen una familia, un bombero y un barco?')
input()
print("no sé... ¿En qué se parecen?")
input()
print('En que el bombero y el barco tienen casco')
input()
print('¿Y la familia?', end='')
print('-Bien, gracias.')
